/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.*;
import static java.lang.Thread.sleep;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Enes
 */
public class MainForm extends javax.swing.JFrame {

	static Color red = new Color(223, 249, 251);
static	Color text= new Color(236, 240, 241);
	static Color green= new Color(186, 220, 88);
	
    static String exePath = "C:\\Tassembly\\DOSBox.exe";
     boolean f= false;
     boolean t= true;
    /**
	 * Creates new form MainForm
	 */
	public MainForm() {




		initComponents();
		getCurrentDate();
		setIcon();
		howP.setVisible(f);
		reqP.setVisible(f);
		comP.setVisible(f);
		B.setBackground(new Color(199, 236, 238));

		JOptionPane.showMessageDialog(null, "Programın sağlıklı çalışması için DOSBox'u Gerekli Programlar sekmesinden yükledikten sonra en az bir defa çalıştırıp kapatınız","Uyarı", HEIGHT,null);
		
		sb(mainP);
		sb(howP);
		sb(reqP);
		sb(comP);
		LP.setBackground(red);
		sb(A1);
		sb(A2);
		
		sbl(mainLabel);
		sbl(howtoLabel);
		sbl(reqLabel);
		sbl(comLabel);

		runLabel.setBackground(new Color(99, 205, 218));
		langP.setBackground(new Color(199, 236, 238));
		
		
		txt1.setBackground(red);
		Date.setForeground(new Color(19,15,64));
		Time.setForeground(new Color(19,15,65));
		mbtn.setBackground(red);

		
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                A1 = new javax.swing.JPanel();
                LP = new javax.swing.JLayeredPane();
                mainP = new javax.swing.JPanel();
                mbtn = new javax.swing.JButton();
                runLabel = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                txt1 = new javax.swing.JTextArea();
                howP = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                txt2 = new javax.swing.JTextArea();
                reqP = new javax.swing.JPanel();
                installbtn = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                reqLab = new javax.swing.JLabel();
                comP = new javax.swing.JPanel();
                A2 = new javax.swing.JPanel();
                sonA = new javax.swing.JLabel();
                mailLabel = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                github = new javax.swing.JLabel();
                mailLabel1 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                facebook = new javax.swing.JLabel();
                B = new javax.swing.JPanel();
                howtoLabel = new javax.swing.JLabel();
                mainLabel = new javax.swing.JLabel();
                comLabel = new javax.swing.JLabel();
                reqLabel = new javax.swing.JLabel();
                langP = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                TR = new javax.swing.JLabel();
                ENG = new javax.swing.JLabel();
                Time = new javax.swing.JLabel();
                Date = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Tassembly");

                A1.setBackground(new java.awt.Color(255, 255, 255));

                mainP.setBackground(new java.awt.Color(255, 255, 255));

                mbtn.setText("Select File");
                mbtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mbtnActionPerformed(evt);
                        }
                });

                runLabel.setBackground(new java.awt.Color(255, 255, 255));
                runLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                runLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                runLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/work.png"))); // NOI18N
                runLabel.setText("Compile");
                runLabel.setToolTipText("");
                runLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                runLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                runLabel.setOpaque(true);
                runLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                runLabelMouseClicked(evt);
                        }
                });

                txt1.setEditable(false);
                txt1.setBackground(new java.awt.Color(255, 204, 204));
                txt1.setColumns(20);
                txt1.setForeground(new java.awt.Color(19, 15, 64));
                txt1.setRows(5);
                txt1.setText("\t\t\tDescription\n\n \tIf you have selected your .asm file\n                                 You can select the file from \"select File\" button  \n\t    Follow the steps below to run the program\n\t\n\t                  On the screen, is called \"DOSBox.exe\" \n\t\t\tyou must give these commands to DOSBox\n\t\n\t1-)  tlink yourAsmFile.obj , for example \"tlink first.obj\"\n\n\t2-)  first.exe , for example \"first.exe\"\n\n                   You must run the DOSBox externally at least once for the program to work properly");
                txt1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jScrollPane1.setViewportView(txt1);

                javax.swing.GroupLayout mainPLayout = new javax.swing.GroupLayout(mainP);
                mainP.setLayout(mainPLayout);
                mainPLayout.setHorizontalGroup(
                        mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(runLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                );
                mainPLayout.setVerticalGroup(
                        mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(runLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(mbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                txt2.setEditable(false);
                txt2.setColumns(20);
                txt2.setRows(5);
                txt2.setText("\n\n\nWhat is DOSBox?\n\nDOSBox is an emulator program which emulates an IBM PC compatible computer running a DOS\noperating system.\n\nWhat is TASM?\n\nTurbo Assembler (TASM) is a computer assembler (software for program development) developed\nby Borland which runs on and produces code for 16- or 32-bit x86 DOS or Microsoft Windows\n\nWhat is intend of this program?\n\n\n");
                jScrollPane2.setViewportView(txt2);

                javax.swing.GroupLayout howPLayout = new javax.swing.GroupLayout(howP);
                howP.setLayout(howPLayout);
                howPLayout.setHorizontalGroup(
                        howPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                );
                howPLayout.setVerticalGroup(
                        howPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                );

                installbtn.setText("Install");
                installbtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                installbtnActionPerformed(evt);
                        }
                });

                jLabel2.setText("DOSBox");

                reqLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                reqLab.setText("DOSBox must be installed to run the program");

                javax.swing.GroupLayout reqPLayout = new javax.swing.GroupLayout(reqP);
                reqP.setLayout(reqPLayout);
                reqPLayout.setHorizontalGroup(
                        reqPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(reqPLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(reqPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(reqPLayout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(113, 113, 113)
                                                .addComponent(installbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 30, Short.MAX_VALUE))
                                        .addGroup(reqPLayout.createSequentialGroup()
                                                .addComponent(reqLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(78, 78, 78))))
                );
                reqPLayout.setVerticalGroup(
                        reqPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(reqPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(reqLab, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(reqPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(installbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(137, Short.MAX_VALUE))
                );

                sonA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                sonA.setText("All rights reserved.");

                mailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                mailLabel.setText(" enesusta@email.com");

                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("My Github Profile");

                github.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                github.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/github.png"))); // NOI18N
                github.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                githubMouseClicked(evt);
                        }
                });

                mailLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                mailLabel1.setText("Facebook");

                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail.png"))); // NOI18N

                facebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/facebook.png"))); // NOI18N
                facebook.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                facebookMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout A2Layout = new javax.swing.GroupLayout(A2);
                A2.setLayout(A2Layout);
                A2Layout.setHorizontalGroup(
                        A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sonA, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                        .addGroup(A2Layout.createSequentialGroup()
                                .addGroup(A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(A2Layout.createSequentialGroup()
                                                .addGap(108, 108, 108)
                                                .addGroup(A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(mailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(github, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(A2Layout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(9, 9, 9))))
                                        .addGroup(A2Layout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(mailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(facebook)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                A2Layout.setVerticalGroup(
                        A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(A2Layout.createSequentialGroup()
                                .addComponent(sonA, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(github, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(A2Layout.createSequentialGroup()
                                                .addComponent(mailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(A2Layout.createSequentialGroup()
                                                .addComponent(facebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );

                javax.swing.GroupLayout comPLayout = new javax.swing.GroupLayout(comP);
                comP.setLayout(comPLayout);
                comPLayout.setHorizontalGroup(
                        comPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(A2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                comPLayout.setVerticalGroup(
                        comPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(A2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                howtoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                howtoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                howtoLabel.setText("How to work?");
                howtoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                howtoLabelMouseClicked(evt);
                        }
                });

                mainLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                mainLabel.setText("Main Menu");
                mainLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                mainLabelMouseClicked(evt);
                        }
                });

                comLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                comLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                comLabel.setText("Communication");
                comLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                comLabelMouseClicked(evt);
                        }
                });

                reqLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                reqLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                reqLabel.setText("Required Programs");
                reqLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                reqLabelMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout BLayout = new javax.swing.GroupLayout(B);
                B.setLayout(BLayout);
                BLayout.setHorizontalGroup(
                        BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(howtoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reqLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(comLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BLayout.createSequentialGroup()
                                        .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 485, Short.MAX_VALUE)))
                );
                BLayout.setVerticalGroup(
                        BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(howtoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addComponent(reqLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mainLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                );

                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lang.png"))); // NOI18N

                TR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                TR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TR.png"))); // NOI18N
                TR.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                TRMouseClicked(evt);
                        }
                });

                ENG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                ENG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/EN.png"))); // NOI18N
                ENG.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ENGMouseClicked(evt);
                        }
                });

                Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                javax.swing.GroupLayout langPLayout = new javax.swing.GroupLayout(langP);
                langP.setLayout(langPLayout);
                langPLayout.setHorizontalGroup(
                        langPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(langPLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ENG, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TR, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                langPLayout.setVerticalGroup(
                        langPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(TR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ENG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                LP.setLayer(mainP, javax.swing.JLayeredPane.DEFAULT_LAYER);
                LP.setLayer(howP, javax.swing.JLayeredPane.DEFAULT_LAYER);
                LP.setLayer(reqP, javax.swing.JLayeredPane.DEFAULT_LAYER);
                LP.setLayer(comP, javax.swing.JLayeredPane.DEFAULT_LAYER);
                LP.setLayer(B, javax.swing.JLayeredPane.DEFAULT_LAYER);
                LP.setLayer(langP, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout LPLayout = new javax.swing.GroupLayout(LP);
                LP.setLayout(LPLayout);
                LPLayout.setHorizontalGroup(
                        LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(langP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(howP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(reqP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                LPLayout.setVerticalGroup(
                        LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LPLayout.createSequentialGroup()
                                .addComponent(langP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LPLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(howP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(58, Short.MAX_VALUE)))
                        .addGroup(LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LPLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(reqP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(64, Short.MAX_VALUE)))
                        .addGroup(LPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LPLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(comP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(66, Short.MAX_VALUE)))
                );

                javax.swing.GroupLayout A1Layout = new javax.swing.GroupLayout(A1);
                A1.setLayout(A1Layout);
                A1Layout.setHorizontalGroup(
                        A1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LP)
                );
                A1Layout.setVerticalGroup(
                        A1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LP)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(A1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(A1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents




	
        private void howtoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtoLabelMouseClicked
		vis(mainP,f);
		vis(howP,t);
		vis(reqP,f);
		vis(comP,f);

		txt2.setText(ENGI);
		txt2.setForeground(new Color(19,15,64));
		txt2.setBackground(red);
		
        }//GEN-LAST:event_howtoLabelMouseClicked

        private void mainLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainLabelMouseClicked
		vis(mainP,t);
		vis(howP,f);
		vis(reqP,f);
		vis(comP,f);
        }//GEN-LAST:event_mainLabelMouseClicked

        private void comLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comLabelMouseClicked
                // TODO add your handling code here:
		vis(mainP,f);
		vis(howP,f);
		vis(reqP,f);
		vis(comP,t);
        }//GEN-LAST:event_comLabelMouseClicked

        private void reqLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reqLabelMouseClicked
                // TODO add your handling code here:
		vis(mainP,f);
		vis(howP,f);
		vis(reqP,t);
		vis(comP,f);
        }//GEN-LAST:event_reqLabelMouseClicked

        private void ENGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENGMouseClicked

		howtoLabel.setText("How to work?");
		reqLabel.setText("Required Programs");
		mainLabel.setText("Main Menu");
		comLabel.setText("Communicate");
		txt1.setText(ENGD);
		
		mbtn.setText("Select File");
		runLabel.setText("Compile");
		txt2.setText(ENGI);
		reqLab.setText(ENGREQ);
		installbtn.setText(ENGB);
		sonA.setText("All rights reserved");
        }//GEN-LAST:event_ENGMouseClicked

        private void TRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TRMouseClicked
		howtoLabel.setText("Nasıl çalışıyor?");
		reqLabel.setText("Gerekli programlar");
		mainLabel.setText("Ana menü");
		comLabel.setText("Iletişim");

		mbtn.setText("Dosya Seç");
		runLabel.setText("Derle");
		txt1.setText(TURD);
		reqLab.setText(TURQ);
		txt2.setText(TURI);
		installbtn.setText(TURB);

	sonA.setText("Bu programın tüm hakları Enes Usta'ya aittir.");
        }//GEN-LAST:event_TRMouseClicked

        private void mbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnActionPerformed
			JFileChooser fileChooser = new JFileChooser();
			JDialog dialog = new JDialog();  
			File selectedFile=null;
			
        
			//    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")+File.separator+"Desktop"));

   	String main = "C:\\Tassembly\\main.conf";
  	String sep = File.separator;
        String userPath = System.getProperty("user.home");
        File path = new File(userPath + sep + "AppData" + sep + "Local" + sep + "DOSBox" + sep + "dosbox-0.74-2.conf");
        File newPath = new File(main);

        try (
             BufferedReader readerC = new BufferedReader(new FileReader(newPath));
             BufferedWriter writerA = new BufferedWriter(new FileWriter(path));
             PrintWriter printWriterA = new PrintWriter(writerA);

        ) {
            Scanner scanC = new Scanner(readerC);
            scanC.useDelimiter(" ");

	    
	    	fileChooser.setCurrentDirectory(new File("C:\\Tassembly"));
              int result = fileChooser.showOpenDialog(dialog);
              if (result == JFileChooser.APPROVE_OPTION) {
                  selectedFile = fileChooser.getSelectedFile();
                  System.out.println("Selected file: " + selectedFile.getAbsolutePath());
              }else{
                  System.out.println("Cancelled");
              }

		// C:\\Users\\Enes\\Desktop
		String currentPath[]=selectedFile.toString().split("\\\\");

		Thread.sleep(500);

	    


            while (scanC.hasNext()) {
                String str = scanC.next();
                printWriterA.print(str);
            }

            printWriterA.println("MOUNT C "+currentPath[0]+File.separator+currentPath[1]);
            printWriterA.println("C:");
            printWriterA.println("TASM "+currentPath[2]);

        } catch (IOException e) {
            e.printStackTrace();
	    JOptionPane.showMessageDialog(null,e);
        }	catch (InterruptedException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);

	    JOptionPane.showMessageDialog(null,ex);
		}




	      
        }//GEN-LAST:event_mbtnActionPerformed

        private void runLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runLabelMouseClicked

		

		executeCommand();
		


        }//GEN-LAST:event_runLabelMouseClicked

        private void installbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installbtnActionPerformed
			
			String exe="C:\\Tassembly\\dbsetup.exe";
			
		try {
			Runtime.getRuntime().exec(exe);
		} catch (IOException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		}
		

        }//GEN-LAST:event_installbtnActionPerformed

        private void facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseClicked
		try {
			final URI uri = new URI("https://www.facebook.com/enes.usta.10441");
			
			Desktop.getDesktop().browse(uri);
		} catch (URISyntaxException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IOException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		}
		
        }//GEN-LAST:event_facebookMouseClicked

        private void githubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_githubMouseClicked

		try {
			final URI uri = new URI("https://github.com/enesusta");
			
			Desktop.getDesktop().browse(uri);
		} catch (URISyntaxException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IOException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		}
		
        }//GEN-LAST:event_githubMouseClicked


	private static void copyFileUsingJava7(File source, File dest) {
		try {
			Files.copy(source.toPath(), dest.toPath());
			
		}catch(IOException e){
			e.printStackTrace();
		}
	}











	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainForm().setVisible(true);
			}
		});
		
	}
	public static void vis(JPanel a,boolean visible){
		a.setVisible(visible);
	}	


	
	public static void sb(JPanel a){
		a.setBackground(red);
	}
	public static void sbl(JLabel a){
		a.setForeground(new Color(19, 15, 64));
	}




public void getCurrentDate(){
		Thread currentClock;
		    currentClock = new Thread() {
			    public void run(){
					String months[]={"Ocak","Şubat","Mart","Nisan",
					"Mayıs","Haziran","Ağustos","Eylül","Ekim","Kasım","Aralık"
					};
					String currentMonth="Ocak";
				    for(;;){
					    Calendar cal = new GregorianCalendar();
						int month=cal.get(Calendar.MONTH);
						int year=cal.get(Calendar.YEAR);
						int day=cal.get(Calendar.DAY_OF_MONTH);
						
						currentMonth=months[month-1];
				
						
				Date.setText("Tarih " +day+" "+currentMonth+" "+year);
						int second=cal.get(Calendar.SECOND);
						int minute=cal.get(Calendar.MINUTE);
						int hour=cal.get(Calendar.HOUR);
							if(minute<10&second<10&hour<12){
								Time.setText("Saat "+(hour+12)+":"+"0"+(minute)+":"+"0"+second);
							}else {
								Time.setText("Saat "+(hour+12)+":"+(minute)+":"+second);
							}

							
							
						    try {
							    sleep(1000);
						    }catch(InterruptedException ex){
					    	}
				    	}
			    	}
		    	};
		currentClock.start();
	}










	
	
    /*public static void main(String[] args) {
        try {
            Thread.sleep(400);
            inputOutputFunction("first.asm");
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
        executCommand();
    }




	
*/
    public static String executeCommand() {
        String line;
        String resultTat = "";

        List<String> arguments = new ArrayList<String>();

        arguments.add(exePath);
        arguments.add("-noconsole");
	
        try {
            Thread.sleep(2000);

            try {
                ProcessBuilder builder;
                builder = new ProcessBuilder(arguments);
                builder.redirectErrorStream(true);

                Process process = builder.start();

                BufferedReader r = new BufferedReader(new InputStreamReader(process.getInputStream()));
                while (true) {
                    line = r.readLine();
                    if (line == null) {
                        break;
                    }
                    resultTat += line + "\n";

                }
            } catch (IOException e) {
                e.printStackTrace();
		JOptionPane.showMessageDialog(null, e);
            }
        } catch (InterruptedException e) {
            e.printStackTrace();
	    JOptionPane.showMessageDialog(null ,e);
        }
        return resultTat;

    }

	private static void cpDOS() {
		List<String> commands = new ArrayList<String>();

		try {
			Runtime.getRuntime().exec("cmd.exe /c start");
			
		} catch (IOException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		}
	
		
		
	}

	private static void executeCMD() {

		try {
			String[] exeCmd = new String[] {"cmd.exe", "C\\Program Files (x86)\\Tassembly\\TASM.exe", 
				"copy", System.getProperty("user.home")+"\\Desktop\\Tassembly"
				
			};
			
			ProcessBuilder pb = new ProcessBuilder(exeCmd);
			
			Process p = pb.start();
		} catch (IOException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		}

	}    


    private static void copyBinaryExeFile() {

   	String main = "C:\\Program Files (x86)\\Tassembly";
	    String path = System.getProperty("user.home")+File.separator+"Desktop";

		File theDir= new File(path+File.separator+"Tassembly");
			
			File outTasm = new File(path+File.separator+"TASM.exe");
			File outTlink = new File(path+File.separator+"TLINK.exe");

			if(!outTasm.exists()) {
				try {
					outTasm.createNewFile();
				}catch(Exception e){
					e.printStackTrace();
				}
			}


			if(!outTlink.exists()) {
				try {
					outTlink.createNewFile();
				}catch(Exception e){
					e.printStackTrace();
				}
			}

	    
		try (
			BufferedInputStream TASM = new BufferedInputStream(new FileInputStream(main+File.separator+"TASM.exe"));
			BufferedInputStream TLINK = new BufferedInputStream(new FileInputStream(main+File.separator+"TLINK.exe"));
			
			BufferedOutputStream TASMO = new BufferedOutputStream(new FileOutputStream(outTasm));
			BufferedOutputStream TLINKO = new BufferedOutputStream(new FileOutputStream(outTlink))
			) {
			
			int i=0;
			int b=0;
			
			
			while((i=TASM.read())!=-1) {
				TASMO.write(i);
			}
			
			while((b=TLINK.read())!=-1) {
				TLINKO.write(b);
			}
			
			TASMO.flush();
			TLINKO.flush();

		} catch (FileNotFoundException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IOException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		}

    }

  



	

	

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel A1;
        private javax.swing.JPanel A2;
        private javax.swing.JPanel B;
        private javax.swing.JLabel Date;
        private javax.swing.JLabel ENG;
        private javax.swing.JLayeredPane LP;
        private javax.swing.JLabel TR;
        private javax.swing.JLabel Time;
        private javax.swing.JLabel comLabel;
        private javax.swing.JPanel comP;
        private javax.swing.JLabel facebook;
        private javax.swing.JLabel github;
        private javax.swing.JPanel howP;
        private javax.swing.JLabel howtoLabel;
        private javax.swing.JButton installbtn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JPanel langP;
        private javax.swing.JLabel mailLabel;
        private javax.swing.JLabel mailLabel1;
        private javax.swing.JLabel mainLabel;
        private javax.swing.JPanel mainP;
        private javax.swing.JButton mbtn;
        private javax.swing.JLabel reqLab;
        private javax.swing.JLabel reqLabel;
        private javax.swing.JPanel reqP;
        private javax.swing.JLabel runLabel;
        private javax.swing.JLabel sonA;
        private javax.swing.JTextArea txt1;
        private javax.swing.JTextArea txt2;
        // End of variables declaration//GEN-END:variables

	private void setIcon() {

		setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/mainIcon.png")));
	}


	String ENGD = "		                 Description\n" +
"" +
" 	If you have selected your .asm file\n" +
"                                 You can select the file from \"select File\" button  \n" +
"	    Follow the steps below to run the program\n" +
"	\n" +
"	                  On the screen, is called \"DOSBox.exe\" \n" +
"			you must give these commands to DOSBox\n" +
"	\n" +
"	1-)  tlink yourAssemlyFile.obj , for example \"tlink first.obj\"\n" +
"\n" +
"	2-)  first.exe , for example \"first.exe\"\n" +
		"		\n\n	You must run the DOSBox externally at least once for the program to work properly";
	String TURD = "		                 Açıklama\n" +
"\n" +
" 	.asm uzantılı Assembly dosyanızı seçtiyseniz\n" +
"                                   \n" +
"	    Programın çalışması için lütfen aşağıdaki adımları takip edin\n" +
"	\n" +
"	                  DOSBox.exe adıyla açılan ekrana  \n" +
"			Aşağı sıra ile verilmiş olan komutları giriniz\n" +
"	\n" +
"	1-)  tlink AssemblyDosyanızınAdı.obj , Örneğin : \"tlink first.obj\"\n" +
"\n" +
"	2-)  first.exe , Örneğin : \"first.exe\"\n" +
"\n" +
"  Programın sağlıklı çalışması için DOSBox'u en az bir defa harici olarak çalıştırmalısınız";

	String ENGI = "\n\n\nWhat is DOSBox?\n" +
"\n" +
"DOSBox is an emulator program which emulates an IBM PC compatible computer running a DOS\n" +
"operating system.\n" +
"\n" +
"What is TASM?\n" +
"\n" +
"Turbo Assembler (TASM) is a computer assembler (software for program development) developed\n" +
"by Borland which runs on and produces code for 16- or 32-bit x86 DOS or Microsoft Windows\n" +
"\n" +
"What is intend of this program?\n" +
"\n" +
"Simply make it easy to compile through TASM.";

	String TURI = "\n\n\nDOSBox nedir?\n" +
"\n" +
"DOSBox bir DOS işletim sistemini çalıştıran IBM bir bilgisayara uyumlu bir emülatör programıdır\n" +
"\n" +
"\n" +
"TASM nedir?\n\n" +
"\n" +
"Turbo Assembler ( TASM ) , Borland tarafından geliştirilen ve 16 veya 32 bit x86 DOS veya Windows \n" +
		"için kod üreten ve çalıştıran bir program geliştirme yazılımıdır\n"+
"\n" +
"Bu programın amacı nedir?"+
"\n" +
"Basitçe TASM aracılığı ile kolay bir şekilde derleme işlemi yapmayı sağlamaktır";


	String ENGREQ= "DOSBox must be installed to run the program";
	String TURQ="Programın çalıştırılabilmesi için DOSBox kurulu olmalıdır.";


	String ENGB="Install the program";
	String TURB="Programı kur";


	
}

